site: WH4LE
title: Blog
greetings: Hello there! 👋
description: >-
  WH4LE (Windows XP)
lang: en-US
timezone:  Europe/Rome
repo: https://github.com/legoskid/legoskid.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: powex # replace with your disqus shortname
comments-enabled: false # true to enable disqus comments, false to hide them

author:
  name: ‎
  bio: WH4LE
  userpicture: 
  username: # general username
  github: legoskid # github username
  twitter: # twitter username
  mastodon: # mastodon profile (ex. mastodon.social/@my_username)
  linkedin: # linkedin profile
  email: ‎ # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap

# URL settings
url: "https://legoskid.github.io" # Domain Name of host. [username].github.io for github pages
#baseurl: "/Gesko" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


